cask_args appdir: '/Applications'

tap 'homebrew/bundle'

brew 'ack'
brew 'coreutils'
brew 'findutils'
brew 'go'
brew 'grc'
brew 'imagemagick'
brew 'jp2a'
brew 'jq'
brew 'kubernetes-cli'
brew 'kubernetes-helm'
brew 'libcaca', args: ['with-imlib2']
brew 'libgit2'
brew 'openssl'
brew 'node'
brew 'readline'
brew 'postgresql'
brew 'python'
brew 'ruby-build'
brew 'rbenv'
brew 'terraform'
brew 'unrar'
brew 'wget'
brew 'yarn'

cask '1password'
cask 'android-studio'
cask 'appcleaner'
cask 'google-chrome'
cask 'intellij-idea'
cask 'java'
cask 'java6'
cask 'java7'
cask 'minikube'
cask 'paw'
cask 'proxifier'
cask 'razer-synapse'
cask 'slack'
cask 'sublime-text'
cask 'transmission'
cask 'transmit'
cask 'vlc'
cask 'spotify'
cask 'xcode'
cask 'zoomus'